### ISSUE TITLE
Build local Website for Development & Testing of new features

### ISSUE THREAD

**Issue by vipulgupta2048** [product-os/docusaurus-builder#41]
Figure out a way to create a website that is built using repo's files & configuration but using the branch's updated action to make use of that website as 

0. Local testing of new features being added to theme 
1. Testing of all existing features supported in theme
2. It would be generally nice to have a website. 

Find a way to use the same branch to build the new website so as to new features.

**Comment by Bucknalla** [comment]
Resolved with #44
